INSERT INTO users (
  id,
  email,
  display_name,
  role,
  password_hash,
  is_active
) VALUES
  (
    'USER-ADMIN',
    'admin@plant.local',
    'Ragav',
    'admin',
    '$2b$12$qekSj9KAF4s6g0pqxwySkeurvNetGsTOs1wLHpd39ZjgXUOAuP7Xi',
    1
  ),
  (
    'USER-MAINTENANCE',
    'maintenance@plant.local',
    'Lokesh',
    'maintenance_engineer',
    '$2b$12$qekSj9KAF4s6g0pqxwySkeurvNetGsTOs1wLHpd39ZjgXUOAuP7Xi',
    1
  ),
  (
    'USER-TECHNICIAN',
    'technician@plant.local',
    'Vinoth',
    'maintenance_technician',
    '$2b$12$qekSj9KAF4s6g0pqxwySkeurvNetGsTOs1wLHpd39ZjgXUOAuP7Xi',
    1
  ),
  (
    'USER-SUPERVISOR',
    'supervisor@plant.local',
    'Dhruv',
    'maintenance_supervisor',
    '$2b$12$qekSj9KAF4s6g0pqxwySkeurvNetGsTOs1wLHpd39ZjgXUOAuP7Xi',
    1
  ),
  (
    'USER-RELIABILITY',
    'reliability@plant.local',
    'Guna',
    'reliability_engineer',
    '$2b$12$qekSj9KAF4s6g0pqxwySkeurvNetGsTOs1wLHpd39ZjgXUOAuP7Xi',
    1
  ),
  (
    'USER-PLANNER',
    'planner@plant.local',
    'Priya',
    'planner',
    '$2b$12$qekSj9KAF4s6g0pqxwySkeurvNetGsTOs1wLHpd39ZjgXUOAuP7Xi',
    1
  ),
  (
    'USER-OPERATOR',
    'operator@plant.local',
    'Jan',
    'operator',
    '$2b$12$qekSj9KAF4s6g0pqxwySkeurvNetGsTOs1wLHpd39ZjgXUOAuP7Xi',
    1
  ),
  (
    'USER-IOT-SERVICE',
    'iot-service@plant.local',
    'Vijay',
    'iot_service',
    '$2b$12$qekSj9KAF4s6g0pqxwySkeurvNetGsTOs1wLHpd39ZjgXUOAuP7Xi',
    1
  )
ON CONFLICT(email) DO UPDATE SET
  id=excluded.id,
  display_name=excluded.display_name,
  role=excluded.role,
  is_active=excluded.is_active;
